# config/routes.yaml
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST

app_logout:
    path: /logout
    methods: GET

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: GET|POST

admin_dashboard:
    path: /admin
    controller: App\Controller\AdminController::dashboard
    methods: GET

front_home:
    path: /
    controller: App\Controller\FrontController::home
    methods: GET

app_user_index:
    path: /user
    controller: App\Controller\UserController::index
    methods: GET

app_user_new:
    path: /user/new
    controller: App\Controller\UserController::new
    methods: GET|POST

app_user_show:
    path: /user/{id}
    controller: App\Controller\UserController::show
    methods: GET

app_user_edit:
    path: /user/{id}/edit
    controller: App\Controller\UserController::edit
    methods: GET|POST

app_user_delete:
    path: /user/{id}
    controller: App\Controller\UserController::delete
    methods: POST
