# config/routes.yaml

# Routes existantes
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST

app_logout:
    path: /logout
    methods: GET

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: GET|POST

admin_dashboard:
    path: /admin
    controller: App\Controller\AdminController::dashboard
    methods: GET

front_home:
    path: /
    controller: App\Controller\FrontController::home
    methods: GET

# Routes User (normales - espace utilisateur)
app_user_index:
    path: /user
    controller: App\Controller\UserController::index
    methods: GET

app_user_new:
    path: /user/new
    controller: App\Controller\UserController::new
    methods: GET|POST

app_user_show:
    path: /user/{id}
    controller: App\Controller\UserController::show
    methods: GET

app_user_edit:
    path: /user/{id}/edit
    controller: App\Controller\UserController::edit
    methods: GET|POST

app_user_delete:
    path: /user/{id}
    controller: App\Controller\UserController::delete
    methods: POST

# NOUVELLES ROUTES ADMIN
# Routes Admin User (module admin) - IMPORTANT: ORDRE DES ROUTES!
admin_user_index:
    path: /admin/users
    controller: App\Controller\Admin\AdminUserController::index
    methods: GET

admin_user_new:
    path: /admin/users/new
    controller: App\Controller\Admin\AdminUserController::new
    methods: GET|POST

# LES ROUTES EDIT ET DELETE DOIVENT ÃŠTRE AVANT SHOW!
admin_user_edit:
    path: /admin/users/{id}/edit
    controller: App\Controller\Admin\AdminUserController::edit
    methods: GET|POST

admin_user_delete:
    path: /admin/users/{id}
    controller: App\Controller\Admin\AdminUserController::delete
    methods: POST

admin_user_show:
    path: /admin/users/{id}
    controller: App\Controller\Admin\AdminUserController::show
    methods: GET

# Routes pour les futurs modules
admin_match_index:
    path: /admin/matches
    controller: App\Controller\Admin\AdminMatchController::index
    methods: GET

admin_team_index:
    path: /admin/teams
    controller: App\Controller\Admin\AdminTeamController::index
    methods: GET
app_acceuil:
    path: /acceuil
    controller: App\Controller\AcceuilController::index
    methods: GET